config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"


  # ruta por defecto
  root "portfolios#index"

  # #RUTAS DE PORTFOLIOS
  # ruta de portafolios
  get "/portfolios", to: "portfolios#index"
  # ruta de creacion de un nuevo portafolio
  get "/portfolios/new", to: "portfolios#new", as: "new_portfolio"
  # ruta para ver un portafolio específico
  get "/portfolios/:id", to: "portfolios#show", as: "portfolio"
  # ruta para reequilibrar un portafolio
  post "/portfolios/:id/rebalance", to: "portfolios#rebalance", as: "rebalance"
  # ruta para reequilibrar un portafolio
  post "/portfolios/:id/rebalance_apply", to: "portfolios#rebalance_apply", as: "rebalance_apply"
  # ruta para crear un portafolio
  post "/portfolios", to: "portfolios#create"
  # ##RUTAS DE STOCKS
  # ruta de stocks
  get "/stocks", to: "stocks#index"
  # ruta de visualizacion de un stock
  get "/stocks/:id", to: "stocks#show", as: "stock"
  # ruta para crear un stock
  post "/stocks", to: "stocks#create", as: "new_stock"
  # ruta para editar un stock
  patch "/stocks/:id/edit", to: "stocks#edit", as: "edit_stock"
  # rutas de aims de stocks en portafolios
  get "/portfolios/:id/portfolio_stock_aims/new", to: "portfolios#newStockAim", as: "portfolio_stock_aims_new"
  delete "/portfolios/:id/portfolio_stock_aims/:stock_id", to: "portfolios#removeStockAim", as: "portfolio_stock_aim"
  post "/portfolios/:id/portfolio_stock_aims/", to: "portfolios#addStockAim", as: "portfolio_stock_aim_add"
  # rutas de stock en portafolios
  post "/portfolios/:id/portfolio_stocks/buy", to: "portfolios#portfolioStockBuy", as: "portfolio_stock_buy"
  post "/portfolios/:id/portfolio_stocks/sell", to: "portfolios#portfolioStockSell", as: "portfolio_stock_sell"
  delete "/portfolios/:id/portfolio_stocks/:stock_id", to: "portfolios#portfolioStockSellAll", as: "portfolio_stock_sell_all"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :portfolio_stocks, dependent: :destroy
    has_many :portfolio_stock_aims, dependent: :destroy

    validates :name, presence: true

    def portfolioStockBuy(stock, price)
        # Verificar si el stock ya existe en el portafolio
        existing_stock = self.portfolio_stocks.find_by(stock_id: stock.id)
        if existing_stock
            # Si el stock ya existe, incrementar la cantidad segun el precio del stock
            existing_stock.quantity += price / stock.price
            if existing_stock.save!
                return true, "Accion comprada y cantidad actualizada en el portafolio."
            else
                return false, existing_stock.errors.full_messages.to_sentence
            end
        else
            # Si el stock no existe, crear una nueva entrada
            new_stock = self.portfolio_stocks.new(stock_id: stock.id, quantity: price / stock.price)
            if new_stock.save!
                return true, "Accion comprada y agregada al portafolio."
            else
                return false, new_stock.errors.full_messages.to_sentence
            end
        end
    end

    def portfolioStockSell(stock_id, price)
        # Verificar si el stock ya existe en el portafolio
        existing_stock = self.portfolio_stocks.find_by(stock_id: stock_id)
        if existing_stock
            @valorizado= existing_stock.quantity * existing_stock.stock.price
            # Si el stock ya existe, decrementar la cantidad
            if @valorizado >= price
                existing_stock.quantity -= price/ existing_stock.stock.price

                # si la cantidad llega a 0, eliminar el stock del portafolio
                if existing_stock.quantity == 0
                    existing_stock.destroy
                    return true, "Accion vendida y eliminada del portafolio."
                else
                    # Guardar los cambios en la cantidad del stock
                    if existing_stock.save!
                        return true, "Accion vendida y cantidad actualizada."
                    else
                        return false, existing_stock.errors.full_messages.to_sentence
                    end
                end
            else
                return false, "No puedes vender más acciones de las que tienes."
            end
        else
            return false, "No se encontró el stock en el portafolio."
        end
    end

    def rebalance
        # metodo con la logica de rebalanceo,
        # esta funcion recorre los stocks del portafolio, suma su cantidad total en precio
        # y luego comparar con los aims de cada stock en cada portfolio y los porcentajes obtenidos
        # y entregar las acciones con los datos que se deben actualizar, ya sea en compra o venta de stocks
        # considera que si hay stocks que no estan en los aims, estos se deben vender
        # en caso de que los aims no sumen 100 no es posible hacer el rebalanceo, se debe retornar un error
        # tener en consideracion que los valores estan siendo redondeados a 1 decimal

        updates = []

        # Obtener todos los stocks del portafolio
        portfolio_stocks = self.portfolio_stocks.includes(:stock)
        # Obtener todos los aims del portafolio
        portfolio_stock_aims = self.portfolio_stock_aims.includes(:stock)

        # suma de los porcentajes de los aims
        total_percentage = portfolio_stock_aims.sum(:percentage)
        # si no suman 100, no se puede hacer el rebalanceo
        if total_percentage != 100
            return [], "No se puede hacer el rebalanceo, los porcentajes de los objetivos no suman 100."
        end

        # Calcular el valor total del portafolio
        total_value = portfolio_stocks.sum("quantity * stocks.price")

        # calculo los porcentajes actuales de cada stock en el portafolio
        current_percentages = {}
        portfolio_stocks.each do |portfolio_stock|
            # Si el stock no tiene un aim asociado, lo vendo
            unless portfolio_stock_aims.any? { |aim| aim.stock_id == portfolio_stock.stock_id }
                # Calculo la cantidad de acciones a vender
                amount_to_sell = portfolio_stock.quantity * portfolio_stock.stock.price
                if amount_to_sell > 0
                    updates.push(StockAction.new("sell", portfolio_stock.stock, amount_to_sell))
                end
            end

            stock_price = portfolio_stock.stock.price
            current_percentages[portfolio_stock.stock.id] = ((portfolio_stock.quantity * stock_price) / total_value * 100).round(1)
        end

        # Recorro los aims y comparo con los stocks del portafolio
        portfolio_stock_aims.each do |aim|
            stock = aim.stock
            aim_percentage = aim.percentage
            current_percentage = current_percentages[stock.id] || 0

            # Si el porcentaje actual es menor que el aim, necesito comprar
            if current_percentage < aim_percentage
                # Calculo la cantidad de acciones a comprar en moneda
                amount_to_buy = ((aim_percentage - current_percentage) / 100.0) * total_value
                # redonde a 1 decimal
                amount_to_buy = amount_to_buy.round(1)
                if amount_to_buy > 0
                    updates.push(StockAction.new("buy", stock, amount_to_buy))
                end
            # Si el porcentaje actual es mayor que el aim, necesito vender
            elsif current_percentage > aim_percentage
                # Calculo la cantidad de acciones a vender en moneda
                amount_to_sell = ((current_percentage - aim_percentage) / 100.0) * total_value
                amount_to_sell = amount_to_sell.round(1)
                if amount_to_sell > 0
                    updates.push(StockAction.new("sell", stock, amount_to_sell))
                end
            end
        end

        return updates, "Rebalanceo completado con #{updates.size} acciones a actualizar."
    end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
    @portfolios = Portfolio.all.order(:id)
  end

  def show
    @portfolio = Portfolio.find(params[:id])
    # sumo los porcentajes de los aims
    @total_percentage = @portfolio.portfolio_stock_aims.sum(:percentage)
    # si es igual a 100, indicio booleano para no permitir agregar mas aims
    @is_full_aim = @total_percentage >= 100

    # obtengo el total de acciones en el portafolio de quantity por valor de stock
    @portfolio_stocks = @portfolio.portfolio_stocks.includes(:stock)
    # si el portafolio no tiene acciones, no se puede calcular el valor total
    @total_value = 0

    if @portfolio_stocks.any?
    @total_value = @portfolio_stocks.sum("quantity * stocks.price")
    end
    if flash[:rebalance].nil?
      flash[:rebalance] = [] # Inicializo el flash para evitar errores si no se ha reequilibrado
    end
  end

  def new
    @portfolio = Portfolio.new
  end

  def rebalance
    @portfolio = Portfolio.find(params[:id])
    @rebalance=@portfolio.rebalance
    # muestro los datos que retorna para ver si se ha reequilibrado correctamente
    flash[:rebalance] = @rebalance[0]
    if @rebalance[0].empty?
      flash[:notice] = @rebalance[1]
    else
      flash[:notice] = @rebalance[1]
    end
    # redirijo a la vista del portafolio
    redirect_to @portfolio
  end

  def rebalance_apply
    @portfolio = Portfolio.find(params[:id])
    @rebalance=@portfolio.rebalance
    # Recorro las acciones a comprar y vender
    @rebalance[0].each do |action|
      stock = action.stock
      amount = action.amount

      if action.action == "buy"
        # Llamo al metodo de compra de acciones del portafolio
        @portfolio.portfolioStockBuy(stock, amount)
      elsif action.action == "sell"
        # Llamo al metodo de venta de acciones del portafolio
        @portfolio.portfolioStockSell(stock.id, amount)
      end
    end

    flash[:notice] = "Balanceo del portafolio aplicado correctamente."
    redirect_to @portfolio and return
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    if @portfolio.save
      redirect_to @portfolio
    else
      render :new, status: :unprocessable_entity
    end
  end


  def newStockAim
    @portfolio = Portfolio.find(params[:id])
    # sumo los porcentajes de los aims
    @total_percentage = @portfolio.portfolio_stock_aims.sum(:percentage)
    # si es igual a 100, indicio booleano para no permitir agregar mas aims
    @is_full_aim = @total_percentage >= 100
    if @is_full_aim
      flash[:error] = "El portafolio ya tiene el 100% de aims asignados."
      redirect_to @portfolio and return
    end
    # si es menor calculor el restante para limitar el porcentaje de los nuevos aims
    @remaining_percentage_aim = 100 - @total_percentage if @total_percentage < 100
  end

  def addStockAim
    @params2 = stockaim_params
    @portfolio = Portfolio.find(params[:id])

    # Verificar si el aim ya existe
    existing_aim = @portfolio.portfolio_stock_aims.find_by(stock_id: @params2[:stock_id])
    if existing_aim
      flash[:error] = "El objetivo para esta accion ya existe."
      redirect_to portfolio_stock_aims_new_path(@portfolio) and return
    end

    # Crear un nuevo aim
    aim = @portfolio.portfolio_stock_aims.create(@params2)
    if aim.save
      redirect_to @portfolio
    else
      flash[:error] = aim.errors.full_messages.to_sentence
      redirect_to @portfolio
    end
  end

  def removeStockAim
    @portfolio = Portfolio.find(params[:id])
    aim = @portfolio.portfolio_stock_aims.find_by_id(params[:stock_id])
    if aim
      aim.destroy
    else
      flash[:error] = "No se encontró un objetivo para esta accion."
    end
    redirect_to @portfolio
  end


  def portfolioStockBuy
    @params2 = stock_params
    @portfolio = Portfolio.find(params[:id])

    # busco stock
    stock = Stock.find_by(id: @params2[:stock_id])

    # verificar si el stock existe
    unless stock
      flash[:error] = "El stock no existe."
      return redirect_to @portfolio
    end
    # llamo funcion de compra de acciones del portafolio
    portfolio_stock = @portfolio.portfolioStockBuy(stock, @params2[:price].to_f)
    if portfolio_stock[0]
      flash[:notice] = portfolio_stock[1]
    else
      flash[:error] = portfolio_stock[1]
    end
    redirect_to @portfolio
  end

  def portfolioStockSell
    @params2 = stock_params
    @portfolio = Portfolio.find(params[:id])
    # llamo funcion de compra de acciones del portafolio
    portfolio_stock = @portfolio.portfolioStockSell(@params2[:stock_id], @params2[:price].to_f)

    if portfolio_stock[0]
      flash[:notice] = portfolio_stock[1]
    else
      flash[:error] = portfolio_stock[1]
    end
    redirect_to @portfolio
  end

  def portfolioStockSellAll
    @portfolio = Portfolio.find(params[:id])
    @portfolio_stock = @portfolio.portfolio_stocks.find_by(id: params[:stock_id])
    if @portfolio_stock
      # Eliminar todas las acciones del stock del portafolio
      @portfolio_stock.destroy
      flash[:notice] = "Todas las acciones del stock \""+@portfolio_stock.stock.identifier+"\" han sido vendidas."
    else
      flash[:error] = "No se encontró el stock en el portafolio."
    end
    redirect_to @portfolio
  end

  private
    def portfolio_params
      params.expect(portfolio: [ :name ])
    end
    def stockaim_params
      params.expect(portfolio_stock_aim: [ :stock_id, :percentage ])
    end
    def stock_params
      params.expect(stock: [ :stock_id, :price ])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/index.html.erb
<h1>Portafolios</h1>
<p>
<%= link_to "Listado de Stocks", stocks_path %>
</p>
</br>

<%= link_to "Crear Portafolio", new_portfolio_path %>
</br>
</br>
<div id="portfolios">
  <% @portfolios.each do |portfolio| %>
    <div>
      <%= portfolio.id %> -
      Portafolio: <%= link_to portfolio.name, portfolio %>
    </div>
  <% end %>
</div>

app/views/portfolios/new.html.erb
<h1>Nuevo Portafolio</h1>

<%= form_with model: @portfolio do |form| %>
  <div>
    <%= form.label 'Nombre' %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit 'Crear Portafolio' %>
  </div>
<% end %>

</br>
</br>
<%= link_to "Volver", portfolios_path %>

app/views/portfolios/newStockAim.html.erb
<h1>Nuevo Objetivo de Stock</h1>

<% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
<% end %>
<%= form_with model: PortfolioStockAim.new, url: portfolio_stock_aim_add_path(@portfolio) do |form| %>
    <div>
        <%= form.label :stock_id, "Accion" %>
        <%= form.collection_select :stock_id, Stock.all, :id, :identifier %>
    </div>

    <div>
        <%= form.label :percentage, "Porcentaje" %>
        <%= form.number_field :percentage,in: 0.1..@remaining_percentage_aim, step: 0.1 %>
    </div>
    <p>Porcentaje restante: <%= @remaining_percentage_aim %>%</p>

    <div>
        <%= form.submit "Crear Objetivo de Stock" %>
    </div>
  </div>
<% end %>


<%= link_to "Volver", portfolio_path(@portfolio) %>

app/views/portfolios/show.html.erb
<h1>Portafolio: <%= @portfolio.name %></h1>

 <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>  

<% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
<% end %>  

<h2>Objetivos</h2>

<div id="portfolio_stock_aims">
    <% if @portfolio.portfolio_stock_aims.empty? %>
        <tr><td>No hay objetivos de stock en este portafolio.</td></tr>
    <% else %>
        <table>
            <tr>
                <th>Nombre de Accion</th>
                <th>Porcentaje objetivo</th>
                <th>Eliminar</th>
            </tr>
        <% @portfolio.portfolio_stock_aims.order(:stock_id).each do |portfolioStocksAim| %>
            <tr>
                <td>
                <%= portfolioStocksAim.stock.identifier %>
                </td>
                <td>
                <%= portfolioStocksAim.percentage %>
                </td>
                <td>
                <%= button_to "Eliminar", portfolio_stock_aim_path(@portfolio.id,portfolioStocksAim.id), method: :delete, data: { turbo_confirm: "¿Estas seguro de eliminar el objetivo?" } %>
                </td>
            </tr>
        <% end %>
        
        </table>

    <% end %>
    
    <% if not @is_full_aim %>
        <div>
        <%= link_to "Nuevo Objetivo de Stock", portfolio_stock_aims_new_path(@portfolio) %>
        </div>
    <% end %>
    
</div>




<h2>Acciones</h2>
<h3>Total Valorizado: <%= @total_value %> $</h3>

<div id="portfolio_stocks">

    <% if @portfolio.portfolio_stocks.empty? %>
    <p>No hay acciones en el portafolio.</p>
    <% else %>



        <table>
            <tr>
                <th>Accion</th>
                <th>Cantidad</th>
                <th>Valorizado</th>
                <th>Vender en $</th>
            </tr>
        <% @portfolio.portfolio_stocks.order(:stock_id).each do |portfolioStocks| %>
            <tr>
                <td>
                <%= portfolioStocks.stock.identifier %>(<%= portfolioStocks.stock.price %>$)
                </td>
                <td>
                <%= portfolioStocks.quantity.round(1) %>
                </td>

                <td>
                <%= portfolioStocks.valorized_price %>$ 
                (<%=((portfolioStocks.valorized_price/@total_value)*100).round(1) %>%)
                </td>

                <td>
                <%= form_with model:Stock.new, url: portfolio_stock_sell_path(@portfolio) do |form| %>
                    <%= form.hidden_field :stock_id, value: portfolioStocks.stock_id %>
                    <%= form.number_field :price, value:0, min:0.1,max:portfolioStocks.quantity * portfolioStocks.stock.price,step:0.1 %>
                    <%= form.submit "Vender",data: { turbo_confirm: "¿Estas seguro de vender?" } %>
                    <% end %>
                    <%= button_to "Vender Todo", portfolio_stock_sell_all_path(@portfolio.id,portfolioStocks.id), method: :delete, data: { turbo_confirm: "¿Estas seguro de vender todo?" } %>

                </td>

            </tr>
        <% end %>
        </table>
    <% end %>
</div>



<h2>Comprar en $</h2>
<div id="portfolio_stock_buy">
    <%= form_with model:Stock.new, url: portfolio_stock_buy_path(@portfolio) do |form| %>
    <%= form.collection_select :stock_id, Stock.all, :id, :identifier_price %>
    <%= form.number_field :price, value:0, min:0.1,step:0.1 %>
    <%= form.submit "Comprar",data: { turbo_confirm: "¿Estas seguro de comprar?" }  %>
    <% end %>
</div>

</br>
</br>
<h2>Rebalanceo</h2>
<%= button_to "Calcular Rebalance", rebalance_path(@portfolio) %>

<% if flash[:rebalance] != [] %>
  <div id="rebalance_result">
    <table>
        <tr>
            <th>Accion</th>
            <th>Operacion</th>
            <th>Valorizado $</th>
        </tr>
    <% flash[:rebalance].each do |rebalance| %>
        <tr>
            <td>
            <%= rebalance["stock"]["identifier"] %>
            </td>
            <td>
            <%= rebalance["action"]=='sell'?'Vender':'Comprar' %>
            </td>
            <td>
            <%= rebalance["amount"] %>$
            </td>
        </tr>
    <% end %>
    </table>
   <%= button_to "Aplicar rebalanceo", rebalance_apply_path(@portfolio.id), method: :post, data: { turbo_confirm: "¿Estas seguro de aplicar?" } %>

  </div>
<% end %>

</br>
</br>
<%= link_to "Volver", portfolios_path %>