config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"


  # ruta por defecto
  root "portfolios#index"

  # #RUTAS DE PORTFOLIOS
  # ruta de portafolios
  get "/portfolios", to: "portfolios#index"
  # ruta de creacion de un nuevo portafolio
  get "/portfolios/new", to: "portfolios#new", as: "new_portfolio"
  # ruta para ver un portafolio específico
  get "/portfolios/:id", to: "portfolios#show", as: "portfolio"
  # ruta para reequilibrar un portafolio
  post "/portfolios/:id/rebalance", to: "portfolios#rebalance", as: "rebalance"
  # ruta para reequilibrar un portafolio
  post "/portfolios/:id/rebalance_apply", to: "portfolios#rebalance_apply", as: "rebalance_apply"
  # ruta para crear un portafolio
  post "/portfolios", to: "portfolios#create"
  # ##RUTAS DE STOCKS
  # ruta de stocks
  get "/stocks", to: "stocks#index"
  # ruta de visualizacion de un stock
  get "/stocks/:id", to: "stocks#show", as: "stock"
  # ruta para crear un stock
  post "/stocks", to: "stocks#create", as: "new_stock"
  # ruta para editar un stock
  patch "/stocks/:id/edit", to: "stocks#edit", as: "edit_stock"
  # rutas de aims de stocks en portafolios
  get "/portfolios/:id/portfolio_stock_aims/new", to: "portfolios#newStockAim", as: "portfolio_stock_aims_new"
  delete "/portfolios/:id/portfolio_stock_aims/:stock_id", to: "portfolios#removeStockAim", as: "portfolio_stock_aim"
  post "/portfolios/:id/portfolio_stock_aims/", to: "portfolios#addStockAim", as: "portfolio_stock_aim_add"
  # rutas de stock en portafolios
  post "/portfolios/:id/portfolio_stocks/buy", to: "portfolios#portfolioStockBuy", as: "portfolio_stock_buy"
  post "/portfolios/:id/portfolio_stocks/sell", to: "portfolios#portfolioStockSell", as: "portfolio_stock_sell"
  delete "/portfolios/:id/portfolio_stocks/:stock_id", to: "portfolios#portfolioStockSellAll", as: "portfolio_stock_sell_all"
end

app/models/stock.rb
class Stock < ApplicationRecord
    validates :identifier, presence: true
    validates :price, presence: true

    def identifier_price
    "#{identifier} (#{price}$)"
    end
end

app/models/stockAction.rb
class StockAction
    def initialize(action, stock, amount)
        @action = action
        @stock = stock
        @amount = amount
    end

    def action
        @action
    end

    def stock
        @stock
    end

    def amount
        @amount
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @stocks = Stock.all
  end

  def create
    @stock = Stock.new(stock_params)
    if @stock.save
      flash[:notice] = "Stock Creado."
      redirect_to "/stocks"
    else
      flash[:error] = @stock.errors.full_messages.to_sentence
      redirect_to "/stocks"
    end
  end

  def edit
    @stock = Stock.find(params[:id])
    if @stock.update(stock_params)
      flash[:notice] = "Stock Modificado."
      redirect_to "/stocks"
    else
      flash[:error] = @stock.errors.full_messages.to_sentence
      redirect_to "/stocks"
    end
  end


  private
    def stock_params
      params.expect(stock: [ :identifier, :price ])
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/index.html.erb
<h1>Stocks</h1>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
<% end %>

<div id="stocks">
    <% if @stocks.empty? %>
        <p>No hay acciones creadas.</p>
    <% else %>
        <table>
            <tr>
                <th>ID</th>
                <th>Identificador</th>
                <th>Precio</th>
                <th>Modificar</th>
            </tr>

        

        <% @stocks.each do |stock| %>
            <tr>
            <%= form_with model: stock, url: edit_stock_path(stock) do |form| %>
                <th>
                <%= stock.id %>
                </th>
                <th>
                <%= form.text_field :identifier %>
                </th>
                <th>
                <%= form.number_field :price, step: 0.1 %>
                </th>
                <th>
                <%= form.submit "Modificar" %>
                </th>
            <% end %>
            </tr>
        <% end %>
        </table>
    <% end %>
</div>

<div id="new_stock">
    <h2>Nuevo Stock</h2>

    <%= form_with model: Stock.new, url: new_stock_path() do |form| %>
        <div>
            <%= form.label "Identificador" %>
            <%= form.text_field :identifier %>
        </div>

        <div>
            <%= form.label "Precio" %>
            <%= form.number_field :price, step: 0.1 %>
        </div>

        <div>
            <%= form.submit "Crear Stock" %>
        </div>
    <% end %>
</div>

</br>
</br>
<%= link_to "Volver", portfolios_path %>